### ISSUE TITLE
show version number/date somewhere

### ISSUE THREAD

**Issue by ralfhauser** [water-fountains/proximap#18]
e.g. as title/mouse-over behind the logo or the info icon

as for the dates, best would be at least two dates:

a) deployment date
b) last committ date

**Comment by mmmatthew** [comment]
I can't find a way to implement this easily and automatically.
Re b), do you mean the date of the last commit on Github or last commit deployed?

**Comment by ralfhauser** [comment]
re b) should git-hash plus last committer (user) automated

re a) also automatically from build system

**Comment by mmmatthew** [comment]
This should help: https://stackoverflow.com/questions/42155115/how-to-include-git-revision-into-angular-cli-application

**Comment by mmmatthew** [comment]
The current implementation in https://github.com/water-fountains/proximap/commit/0eb0a090e346e8ea8c87df316ee525142b16c161 is such:
commit and commit time are visible in the "about" tab of the information panel

Since we have continuous deployment, deployment time is just a few minutes later than commit time. Is it still important for you to have?

**Comment by ralfhauser** [comment]
Cool 
![image](https://user-images.githubusercontent.com/1681677/56077315-f0758c80-5dda-11e9-8da7-99b1aa667657.png)
